# Change these first
owner: Chapati-Systems # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Auth Service
    url: $AUTH_SERVICE
  - name: Alphalerts
    url: https://alphalerts.com/
  - name: OS.MONEY
    url: https://os.money
  - name: Autoupdate API
    url: $AUTOUPDATE_API
  - name: Tasty Stream
    url: https://tasty.stream/
  - name: Gitea
    url: $GITEA
  - name: Project Management
    url: $KANBOARD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.chapati.systems
  # baseUrl: /your-repo-name
  logoUrl: https://chapati.systems/icon192.png
  name: Chapati Systems GmbH Status
  introTitle: "Current Status of the Systems"
  introMessage: See if something is affected.
  navbar:
    - title: Status
      href: /
    - title: Twitter
      href: https://twitter.com/ChapatiSystems
    - title: Privacy Policy
      href: https://chapati.systems/privacy/
    - title: Imprint
      href: https://chapati.systems/imprint/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
